server:
  port: 8085

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/notification-service-DB
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    consumer:
      properties:
        spring.json.trusted.packages: "com.lumina_bank"

  cloud:
    function:
      definition: emailVerificationRequestedConsumer;
                  userRegisteredConsumer;
                  userLoginConsumer;
                  paymentCompletedConsumer;
                  paymentFlaggedConsumer;
                  paymentBlockedConsumer;
                  paymentReminderConsumer

    stream:
      bindings:
        emailVerificationRequestedConsumer-in-0:
          destination: email-verification-events
          group: notification-service
          content-type: application/json

        userRegisteredConsumer-in-0:
          destination: user-registered-events
          group: notification-service
          content-type: application/json

        userLoginConsumer-in-0:
          destination: user-login-events
          group: notification-service
          content-type: application/json

        paymentCompletedConsumer-in-0:
          destination: payments-completed
          group: notification-service
          content-type: application/json

        paymentFlaggedConsumer-in-0:
          destination: payments-flagged
          group: notification-service
          content-type: application/json

        paymentBlockedConsumer-in-0:
          destination: payments-blocked
          group: notification-service
          content-type: application/json

        paymentReminderConsumer-in-0:
          destination: payments-reminder
          group: notification-service
          content-type: application/json

      kafka:
        binder:
          brokers: localhost:9092

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

app:
  mail:
    from: luminabank.app@gmail.com
    from-name: LuminaBank