package com.lumina_bank.aiassistantservice.domain.enums;

public enum Intent {
    CHECK_BALANCE,

    CREATE_ACCOUNT,
    CREATE_CARD,

    LIST_ACCOUNTS,
    LIST_CARDS,
    LIST_ACCOUNT_CARDS,

    USER_INFORMATION,
    UPDATE_USER_INFORMATION,

    PAYMENT_HISTORY,
    TRANSFER_BY_CARD,
    PAYMENT_SERVICE_PROVIDER,
    LIST_PAYMENT_TEMPLATES,
    PAYMENT_BY_TEMPLATE,

    UNKNOWN
}
